"""Local NDJSON engine. Credentials travel through pipes, never files or logs."""
import json
import os
import sys
from http.cookiejar import Cookie

from yt_dlp import YoutubeDL
from yt_dlp.version import __version__


def emit(kind, **data):
    print(json.dumps({'kind': kind, **data}, ensure_ascii=False), flush=True)


class Logger:
    def debug(self, message):
        if not message.startswith('[debug]'):
            emit('log', message=message)

    def info(self, message):
        emit('log', message=message)

    def warning(self, message):
        emit('log', message=message)

    def error(self, message):
        emit('log', message=message)


def main():
    request = json.load(sys.stdin)
    operation = request['operation']
    if operation == 'version':
        emit('result', result={'version': __version__})
        return
    profile = request.get('profile')
    logger = Logger()
    options = {
        'logger': logger, 'quiet': True, 'no_warnings': False,
        'socket_timeout': request.get('timeout', 30), 'retries': request.get('retries', 3), 'fragment_retries': request.get('retries', 3),
        'ratelimit': request.get('speedLimit') or None,
        'noplaylist': False, 'playlistend': 100, 'cachedir': False,
        'ffmpeg_location': request.get('ffmpeg'),
        'js_runtimes': {'node': {'path': request['node']}} if request.get('node') else {},
    }
    # Without this YouTube hands back its English machine translation of the title, not the original.
    youtube_language = {'zh': 'zh-CN', 'zh-tw': 'zh-TW', 'ja': 'ja', 'en': 'en'}.get(request.get('locale', ''))
    if youtube_language:
        options['extractor_args'] = {'youtube': {'lang': [youtube_language]}}
    if operation == 'extract' and request.get('flat', True):
        # Listing a playlist otherwise costs one full extraction per entry - 68s for a 73 video
        # channel against 1.7s here. Formats are resolved when that entry is actually downloaded.
        # The caller asks again without this when an extractor returns entries with no metadata.
        options['extract_flat'] = 'in_playlist'
    if request.get('headers'):
        options['http_headers'] = request['headers']
    if profile:
        options['cookiesfrombrowser'] = (profile['browser'], profile['path'], None, None)
    if operation == 'download':
        options.update({
            'outtmpl': request['output'], 'continuedl': True, 'overwrites': False,
            # One long-lived connection for a whole file is what gets cut: a 334 MiB download was
            # measured dying at 90% when a CDN edge tired of it, and the read timeout that follows
            # costs the whole attempt. Asking for it in ranges means a cut loses one range, not the
            # transfer, and the next one opens a fresh connection.
            'http_chunk_size': 10 * 1024 * 1024,
            'windowsfilenames': True, 'restrictfilenames': False,
            'format': request.get('format', 'bv*+ba/b'), 'merge_output_format': 'mp4/mkv',
            'progress_hooks': [lambda d: emit('progress', status=d['status'],
                downloaded=d.get('downloaded_bytes', 0), total=d.get('total_bytes') or d.get('total_bytes_estimate'),
                speed=d.get('speed'), eta=d.get('eta'))],
        })
        subtitles = request.get('subtitles', 'off')
        if request.get('audioOnly'):
            options['format'] = 'bestaudio/best'
            options['postprocessors'] = [{'key': 'FFmpegExtractAudio', 'preferredcodec': request.get('audioFormat', 'mp3'), 'preferredquality': '192'}]
            # An audio file has nowhere to put a subtitle track and no picture to read it against.
            subtitles = 'off'
        if subtitles != 'off':
            languages = [lang.strip() for lang in request.get('subtitleLanguages', '').split(',') if lang.strip()]
            options.update({
                'writesubtitles': True,
                'writeautomaticsub': bool(request.get('subtitleAutoGenerated')),
                # live_chat is a chat replay, not a subtitle, and it is megabytes of JSON.
                'subtitleslangs': (languages or ['en']) + ['-live_chat'],
                'subtitlesformat': 'srt/vtt/best',
            })
            # yt-dlp keeps the manual track when a language has both a manual and an automatic one,
            # so enabling automatic subtitles cannot produce two tracks of the same language.
            options.setdefault('postprocessors', [])
            if subtitles == 'embed':
                options['postprocessors'].append({'key': 'FFmpegEmbedSubtitle', 'already_have_subtitle': False})
            else:
                options['postprocessors'].append({'key': 'FFmpegSubtitlesConvertor', 'format': 'srt'})
        # Covers. One flag writes the picture, one post-processor puts it inside the media file, and
        # they are independent: embedding without keeping asks yt-dlp to delete the picture afterwards,
        # which 'already_have_thumbnail' is how it is told not to.
        save_thumbnail = bool(request.get('saveThumbnail'))
        embed_thumbnail = bool(request.get('embedThumbnail'))
        if save_thumbnail or embed_thumbnail:
            options['writethumbnail'] = True
            options.setdefault('postprocessors', [])
            # Conversion has to happen before the picture is embedded, or the original travels inside
            # the media file while the converted one sits beside it.
            if request.get('thumbnailFormat') == 'jpg':
                options['postprocessors'].append({'key': 'FFmpegThumbnailsConvertor', 'format': 'jpg', 'when': 'before_dl'})
            if embed_thumbnail:
                # Appended last so it runs after FFmpegExtractAudio: an audio file that does not exist
                # yet has nowhere to put a cover.
                options['postprocessors'].append({'key': 'EmbedThumbnail', 'already_have_thumbnail': save_thumbnail})
        if request.get('entry'):
            options['playlist_items'] = str(request['entry'])
    files = []
    with YoutubeDL(options) as ydl:
        # Inject a domain-aware cookie jar from an authorized Chrome connection.
        for item in request.get('cookies', []):
            domain = item['domain']
            ydl.cookiejar.set_cookie(Cookie(0, item['name'], item['value'], None, False,
                domain, domain.startswith('.'), domain.startswith('.'), item.get('path', '/'), True,
                item.get('secure', False), int(item['expires']) if item.get('expires', -1) > 0 else None,
                False, None, None, {}, False))
        if operation == 'download':
            from yt_dlp.postprocessor.common import PostProcessor

            keep_subtitle_files = request.get('subtitles') == 'file' and not request.get('audioOnly')

            class CaptureFile(PostProcessor):
                def run(self, info):
                    files.append(info['filepath'])
                    # Sidecar subtitles are separate files the client has to know about. In embed mode
                    # they are deleted once muxed in, so their recorded paths no longer exist.
                    if keep_subtitle_files:
                        for track in (info.get('requested_subtitles') or {}).values():
                            saved = track.get('filepath')
                            if saved and saved not in files and os.path.exists(saved):
                                files.append(saved)
                    # Same for the cover picture: a file the client does not know about is one it will
                    # not clean up when the task is deleted and will not show in the file list. Embed
                    # without save deletes it, which is what the existence check is for.
                    if save_thumbnail:
                        for picture in (info.get('thumbnails') or []):
                            saved = picture.get('filepath')
                            if saved and saved not in files and os.path.exists(saved):
                                files.append(saved)
                    return [], info

            ydl.add_post_processor(CaptureFile(ydl), when='after_move')
        info = ydl.extract_info(request['url'], download=operation == 'download')
        emit('result', result=ydl.sanitize_info(info) if operation == 'extract' else {'files': files})


if __name__ == '__main__':
    try:
        main()
    except Exception as error:
        # Do not emit tracebacks / request data: either can contain credentials.
        emit('error', message=str(error))
        sys.exit(1)
