import { z } from 'zod'
import { i18n } from './i18n'

export const settingsSchema = z.object({
  browserProfileId: z.string().max(200).nullable().default(null),
  concurrency: z.number().int().min(1).max(4).default(2),
  resumeOnStart: z.boolean().default(false),
  notifications: z.boolean().default(true),
  minimizeToTray: z.boolean().default(false),
  speedLimit: z.number().int().min(0).max(1048576).default(0),
  taskSpeedLimit: z.number().int().min(0).max(1048576).default(0),
  retries: z.number().int().min(0).max(10).default(3),
  // The most tasks one 下载所选 may create, taken in listing order; 0 is no limit. 20 by default: a
  // listing now grows by 加载更多 and 全选 takes all of it, so without a cap one click can queue
  // hundreds of posts, which is rarely what is meant. The result area says when the cap applied.
  batchLimit: z.number().int().min(0).max(500).default(20),
  timeout: z.number().int().min(5).max(300).default(30),
  filenameTemplate: z.enum(['title-id', 'id-title', 'date-title-id']).default('title-id'),
  organizeByPlatform: z.boolean().default(false),
  // A collection or a multi-part video is one thing split into files, so its parts are kept together
  // under a directory named after it. On by default: a 87-part 合集 dropped into the download folder
  // alongside everything else is the case this exists for.
  organizeByCollection: z.boolean().default(true),
  // 'best' keeps the platform's own best audio as it is, with no conversion; the others convert to it.
  audioFormat: z.enum(['best', 'mp3', 'm4a', 'flac']).default('best'),
  // Covers. The two that change what a download produces are off by default: saving one puts a second
  // file beside every video, embedding one rewrites the video file itself, and neither is something a
  // user asked for by pressing download. The right-click actions are there whenever they do want one.
  saveThumbnail: z.boolean().default(false),
  embedThumbnailInVideo: z.boolean().default(false),
  // Audio is the exception: a music file without cover art is the one that looks wrong, so this is on.
  embedThumbnailInAudio: z.boolean().default(true),
  // Platforms mostly serve webp, which Windows Explorer previews inconsistently; 'jpg' converts.
  thumbnailFormat: z.enum(['original', 'jpg']).default('original'),
  videoQuality: z.enum(['best', '1080', '720', '480']).default('best'),
  subtitles: z.enum(['off', 'embed', 'file']).default('embed'),
  // Empty follows the interface language; otherwise a yt-dlp language list such as 'zh-Hans,en'.
  subtitleLanguages: z.string().trim().max(200).default(''),
  subtitleAutoGenerated: z.boolean().default(true),
  // Whether successful parses are remembered on the new-task page. On by default; off stops recording
  // without deleting what is already there, which 清空 does.
  keepHistory: z.boolean().default(true),
  view: z.enum(['list', 'grid']).default('list'),
  // 'auto' lets the parse result pick per content: covers for listings and pictures, rows for one video.
  resultView: z.enum(['auto', 'list', 'grid']).default('auto'),
  density: z.enum(['comfortable', 'compact']).default('comfortable'),
  theme: z.enum(['system', 'light', 'dark']).default('system'),
  // The window's language, and the one the client asks platforms for. Only Chinese and English: a
  // setting saved as 繁体中文 or 日本語 by an earlier version reads as the closer of the two.
  locale: z.preprocess(value => value === undefined || value === 'zh-tw' ? 'zh' : value === 'ja' ? 'en' : value, z.enum(['zh', 'en'])),
  // 详细日志: every request, wait and reply head goes to the log file, not only what the client did.
  verboseLogging: z.boolean().default(false),
  // Whether the `galaxy` command line and the agents that use it may drive this client over its local
  // channel. On by default; off stops the client listening at all.
  allowControl: z.boolean().default(true),
})
// There is no proxy setting: every request follows whatever proxy the system itself is configured with,
// which is where a user who runs one has already set it.
export type Settings = z.infer<typeof settingsSchema> & { downloadDirectory: string }
export type BrowserProfile = { id: string; browser: 'chrome' | 'edge' | 'firefox'; label: string; available: boolean }
// 'size' is the whole download at this tier in bytes - the video stream plus the best audio it is
// merged with - as the platform states it, or bitrate times duration where it only states a bitrate.
// 'bitrate' is that same total in kbit/s, which is what lets a listing's sampled tier be estimated for
// every other entry from its duration alone.
// 'preferredSize' / 'preferredBitrate' are the same for the variant a default download takes at this
// height, which is not the one 'id' names: picking a tier downloads its AVC variant, while 默认画质
// lets the engine take its own preference - HEVC on 哔哩哔哩, VP9 on YouTube - which can be half the size.
export type Format = { id: string; label: string; height?: number; audioOnly: boolean; extension: string; size?: number; bitrate?: number; preferredSize?: number; preferredBitrate?: number }
// Counts, author and publish time are what the platform happened to include in its listing: every one of
// them is missing somewhere, so a card shows whichever it was given and leaves no gap for the rest.
export type MediaStats = { views?: number; danmaku?: number; comments?: number; likes?: number; author?: string; publishedAt?: number }
// 'url' is the post's own page, which only a listing has: every item of a single parse belongs to the
// one page the result already names. It travels so the window can offer the link without asking again.
// 'wall' marks an item the platform says this account cannot have as it stands - a paid 短剧 episode -
// known before anything is downloaded. Such an item is shown but cannot be picked.
export type MediaItem = MediaStats & { id: string; title: string; url?: string; duration?: number; thumbnail?: string; kind: 'video' | 'audio' | 'image'; formats: Format[]; wall?: AccessWall }
// A creator profile is served one page at a time; the next page is fetched only when the user asks for it.
export type Pagination = { index: number; size: number; total?: number; hasMore: boolean }
// What kind of listing produced a result. Both kinds are made of separate posts with pages of their
// own, which is what decides how a download names itself; only a collection is saved to a directory.
export type ListingKind = 'profile' | 'collection'
// One tab of a result. A listing is usually a single group, so no tab is shown; a 哔哩哔哩 video that is
// both multi-part and part of a collection is two, and each turns its pages on its own.
// 'directory' is the name this group's downloads are filed under, which only a collection has.
export type MediaGroup = { id: string; title: string; directory?: string; itemIds: string[]; pagination?: Pagination }
// 'truncated' is set where the engine stopped short of the whole playlist rather than reaching its end,
// so the window can say how many were listed instead of presenting a cut-off list as the complete one.
// 'formats' is a listing's quality tiers, read off its first video after the listing arrives - a
// listing's entries carry none of their own. A tier picked from it applies to every video queued; one
// that a later video does not have is downloaded at its best instead.
export type MediaResult = { id: string; url: string; title: string; platform: string; method: 'direct' | 'browser'; listing?: ListingKind; groups?: MediaGroup[]; items: MediaItem[]; truncated?: { shown: number; total?: number }; formats?: Format[] }
// Four different reasons a platform holds something back, each with a different answer. Kept apart
// because "解析失败" for all four tells the user nothing: a sign-in fixes 'login', an entitled account
// fixes the middle two, and nothing fixes 'encrypted'.
export type AccessWall = 'login' | 'membership' | 'purchase' | 'encrypted'
export type JobStatus = 'queued' | 'running' | 'paused' | 'completed' | 'cancelled' | 'failed'
// The parse-time description of the media travels with the job: once the result is gone, the task
// detail is the only place left that can say who published it and when.
export type Job = MediaStats & {
  id: string; url: string; itemId: string; sourceUrl?: string; title: string; platform: string; method: 'direct' | 'browser';
  format: string; audioOnly: boolean; status: JobStatus; progress: number; speed?: number; eta?: number;
  kind?: MediaItem['kind']; thumbnail?: string; duration?: number; downloaded?: number; total?: number; completedAt?: string;
  speedLimit?: number; filenameTemplate?: Settings['filenameTemplate']; videoQuality?: Settings['videoQuality']; audioFormat?: Settings['audioFormat'];
  subtitles?: Settings['subtitles']; subtitleLanguages?: string; subtitleAutoGenerated?: boolean;
  // Taken from the settings when the job was made, like the rest of these: changing a setting must not
  // change what a job already queued is going to produce.
  saveThumbnail?: boolean; embedThumbnail?: boolean; thumbnailFormat?: Settings['thumbnailFormat'];
  // How many times this job has broken off and been picked up again on its own. Reset by finishing and
  // by the user asking for a retry themselves, so a run of automatic attempts is bounded per break.
  attempts?: number
  // One enqueue makes one batch. The whole batch can be paused, resumed, retried, cancelled or
  // deleted at once, while every task in it keeps its own controls. The title is carried on the job
  // rather than kept in a second store, so a batch survives a restart without anything else having to.
  batchId?: string; batchTitle?: string
  // A task that saves the post's cover and nothing else: 'thumbnail' is what it downloads, and the post
  // is never resolved again for it.
  coverOnly?: boolean
  // Which permission wall the last failure ran into, where it named one - the same four the parse page
  // tells apart, so the task detail can say which it was and offer the login window only where a
  // sign-in could help. Read only alongside 'error'.
  wall?: AccessWall
  files: string[]; directory: string; createdAt: string; error?: string; logs: string[]
}
export type ToolInfo = { available: boolean; version: string; error?: string }
// One successful parse, kept so it can be parsed again from the new-task page. The address is the one
// actually parsed (a short link already followed); one entry per address, newest first. Stored beside
// the jobs in the client's own data file and nowhere else.
export type HistoryEntry = {
  url: string; title: string; platform: string; listing?: ListingKind | 'parts'; count: number
  thumbnail?: string; parsedAt: string
}
export type ClientState = {
  settings: Settings; profiles: BrowserProfile[]; jobs: Job[]; history: HistoryEntry[];
  tools: { engine: ToolInfo; ffmpeg: ToolInfo };
  // 'wall' says which permission wall a failure ran into, where it named one. Signing in fixes the
  // first; the other three are the account's own entitlement, and the client works around none of them.
  // 'verify' marks a risk-control challenge rather than a wall: the platform wants its own check passed
  // on its page, which the same window opens as '打开验证页面'.
  parse: { status: 'idle' | 'parsing' | 'needs-login' | 'error'; message?: string; result?: MediaResult; loginUrl?: string; wall?: AccessWall; verify?: boolean };
  // Login state the client holds itself, in its own browser partition.
  browser: { sites: number };
  update: { status: 'idle' | 'checking' | 'available' | 'downloading' | 'ready' | 'error'; version?: string; progress?: number; message?: string };
  // The item whose page is open in the preview dialog. Held here rather than in the window, because
  // the page itself can close it too: Esc pressed inside it never reaches the window.
  preview?: { title: string };
  // The `galaxy` command: whether its launcher is installed, where, and whether that directory is
  // already on the PATH a new terminal gets.
  commandLine: { installed: boolean; launcher: string; onPath: boolean };
}
export const parseInput = z.object({ url: z.string().trim().min(1).max(8192) })
// What to download of each item, any combination: the media itself at 'format', its audio alone (a
// picture has none and is skipped), its cover picture (an item without one is skipped). Each kind is
// a task of its own.
export const downloadKinds = ['video', 'audio', 'cover'] as const
export type DownloadKind = typeof downloadKinds[number]
export const downloadInput = z.object({ resultId: z.string().uuid(), itemIds: z.array(z.string().min(1).max(500)).min(1).max(500), format: z.string().max(200).default('best'), kinds: z.array(z.enum(downloadKinds)).min(1).max(3).default(['video']) })
// 'copy-link', 'open-page' and 'copy-path' are named as actions on the job rather than taking an
// address from the window, because the window does not have one: job urls are redacted on their way
// out, so a link copied from what it holds would be missing everything after the '?'.
// 'login' opens the login window on the job's own page, for a job that failed on a sign-in wall.
// 'thumbnail' saves one cover next to the job's files; 'audio' adds a second job for the same post,
// audio only. Both add to what is on disk and never touch the job they were asked on.
export const jobActionInput = z.object({ id: z.string().uuid(), action: z.enum(['pause', 'resume', 'retry', 'cancel', 'open', 'reveal', 'copy-link', 'open-page', 'copy-path', 'thumbnail', 'audio', 'login']) })
export const commandSchemas = {
  'state:get': z.null(), 'clipboard:read': z.null(), 'browser:refresh': z.null(), 'browser:clear': z.null(),
  'clipboard:write': z.object({ text: z.string().max(8192) }),
  // Hands an address to whatever the system opens links with. Only ever http(s): a renderer that could
  // name any scheme could ask the host to open a file or run a handler, which is not what a link is.
  'shell:open': z.object({ url: z.url().refine(value => /^https?:\/\//i.test(value), { error: () => i18n.t('errors:contracts.webLinkOnly') }) }),
  'browser:login': z.object({ url: z.union([z.literal(''), z.url()]).default('') }),
  'media:parse': parseInput, 'media:cancel': z.null(), 'media:download': downloadInput,
  // 'groupId' names the tab being turned; a result with one group leaves it off and gets that one.
  'media:page': z.object({ resultId: z.string().uuid(), page: z.number().int().min(1).max(500), groupId: z.string().min(1).max(100).optional() }),
  // Watching one item before downloading it. Named by id, like a download: the main process decides
  // what to open, so the window never hands it an address to load.
  'media:preview': z.object({ resultId: z.string().uuid(), itemId: z.string().min(1).max(500) }),
  // Where the preview dialog's page area is, in the window's CSS pixels, each time it moves or resizes.
  'preview:place': z.object({ x: z.number().int().min(0).max(100000), y: z.number().int().min(0).max(100000), width: z.number().int().min(0).max(100000), height: z.number().int().min(0).max(100000) }),
  'preview:close': z.null(),
  'settings:save': settingsSchema, 'settings:directory': z.null(),
  'jobs:action': jobActionInput,
  // Without a batchId this is the whole list, which is what 开始全部 / 暂停全部 have always been; with
  // one it is that batch and nothing else. 'deleteFiles' only ever applies to 'remove'.
  'jobs:batch': z.object({ action: z.enum(['pause', 'resume', 'retry', 'cancel', 'remove']), batchId: z.string().uuid().optional(), deleteFiles: z.boolean().default(false) }),
  'jobs:limit': z.object({ id: z.string().uuid(), speedLimit: z.number().int().min(0).max(1048576) }), // Clearing records is about the list; the files are a separate thing to ask for, and off unless asked.
  'jobs:clear': z.object({ deleteFiles: z.boolean().default(false) }),
  // Only ever about the list: forgetting a parse deletes nothing that was downloaded from it.
  'history:remove': z.object({ url: z.string().min(1).max(8192) }), 'history:clear': z.null(),
  // A parse result's cover, saved where the user picks. Only an http(s) address, like 'shell:open'.
  'media:cover': z.object({ url: z.url().refine(value => /^https?:\/\//i.test(value), { error: () => i18n.t('errors:contracts.webImageOnly') }), title: z.string().max(500).default('封面') }),
  'jobs:remove': z.object({ id: z.string().uuid(), deleteFiles: z.boolean().default(false) }),
  // Whether each file a job recorded is still on disk, and how big it is, for the task detail.
  'jobs:files': z.object({ id: z.string().uuid() }),
  // The command line's own. 'cli:parse' parses without touching the window's result, so an agent
  // working in the background never replaces what the user is looking at.
  'cli:hello': z.null(),
  'cli:parse': z.object({ url: z.string().trim().min(1).max(8192), page: z.number().int().min(1).max(500).default(1) }),
  'cli:install': z.null(), 'cli:uninstall': z.null(),
  'logs:export': z.null(), 'logs:open': z.null(),
  'tools:check': z.null(), 'update:check': z.null(), 'update:download': z.null(), 'update:install': z.null(),
} as const
export type Command = keyof typeof commandSchemas
export type CommandInput<C extends Command> = z.input<(typeof commandSchemas)[C]>
// 'added' is how many downloads a request actually started: asking for something already queued adds
// nothing, and the window says what happened rather than what was asked for.
// 'files' answers 'jobs:files': a file that is gone has no size.
export type JobFile = { path: string; exists: boolean; size?: number }
// 'result', 'jobIds' and 'version' answer the command line; a refusal says which wall it hit, or that a
// verification is wanted, so the command line can tell a sign-in apart from a failure.
export type Reply = { ok: true; state: ClientState; clipboardText?: string; added?: number; files?: JobFile[]; result?: MediaResult; jobIds?: string[]; version?: string }
  | { ok: false; message: string; wall?: AccessWall; verify?: boolean; loginUrl?: string }
export interface DesktopApi {
  command<C extends Command>(command: C, input: CommandInput<C>): Promise<Reply>
  subscribe(listener: (state: ClientState) => void): () => void
}
