import path from 'node:path'
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { createServer } from 'node:http'
import { execFileSync } from 'node:child_process'
import { expect, test, _electron as electron } from '@playwright/test'
const root = path.resolve(import.meta.dirname, '../..')
test('real engine parses and downloads a local video, persists history, and isolates renderer', async () => {
  test.setTimeout(120_000)
  const directory = await mkdtemp(path.join(tmpdir(), 'galaxy-e2e-'))
  const fixture = path.join(directory, 'sample.mp4')
  const ffmpeg = path.join(root, 'node_modules/ffmpeg-static', process.platform === 'win32' ? 'ffmpeg.exe' : 'ffmpeg')
  execFileSync(ffmpeg, ['-hide_banner', '-loglevel', 'error', '-f', 'lavfi', '-i', 'color=c=blue:s=160x90:d=1', '-f', 'lavfi', '-i', 'sine=frequency=440:duration=1', '-c:v', 'libx264', '-c:a', 'aac', '-shortest', fixture])
  const bytes = await readFile(fixture)
  const server = createServer((req, res) => { res.setHeader('content-type', 'video/mp4'); res.setHeader('content-length', bytes.length); if (req.method === 'HEAD') res.end(); else res.end(bytes) })
  await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve))
  await writeFile(path.join(directory, 'state.json'), JSON.stringify({ version: 1, settings: { downloadDirectory: directory }, jobs: [] }))
  // Windows treats an empty value as set, which would start Electron as plain Node and never open a window.
  const env = { ...process.env, CLIENT_TEST_DATA: directory }
  delete env.ELECTRON_RUN_AS_NODE
  let app = await electron.launch({ args: ['.', '--no-sandbox'], cwd: root, env })
  try {
    let page = await app.firstWindow()
    const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
    await expect(page.getByRole('heading', { name: '全部任务', exact: true, level: 1 })).toBeVisible()
    await page.screenshot({ path: 'test-results/home.png', fullPage: true })
    await page.getByRole('button', { name: '新建任务', exact: true }).first().click()
    expect(await page.evaluate(() => ({ node: typeof (window as unknown as { require?: unknown }).require, generic: typeof (window as unknown as { ipcRenderer?: unknown }).ipcRenderer }))).toEqual({ node: 'undefined', generic: 'undefined' })
    expect(await page.evaluate(() => window.desktopApi.command('open-win' as never, null as never))).toMatchObject({ ok: false })
    await page.getByRole('textbox', { name: '媒体链接' }).fill(`http://127.0.0.1:${(server.address() as { port: number }).port}/sample.mp4`)
    await expect(page.getByRole('button', { name: '解析', exact: true })).toBeEnabled({ timeout: 30_000 })
    await page.getByRole('button', { name: '解析', exact: true }).click()
    // The first item comes selected, so a single result is ready to download without picking anything.
    // The wait is for the parse itself, which is what takes the time here.
    await page.getByRole('button', { name: '下载所选 (1)' }).click({ timeout: 40_000 })
    await page.getByRole('button', { name: /^已完成/ }).click()
    await expect(page.getByRole('button', { name: '打开文件位置' })).toBeVisible({ timeout: 40_000 })
    const state = await page.evaluate(() => window.desktopApi.command('state:get', null))
    expect(state.ok).toBe(true)
    if (!state.ok) throw new Error(state.message)
    expect(await readFile(state.state.jobs[0].files[0])).toEqual(bytes)
    await page.getByRole('button', { name: /^查看任务/ }).click()
    await expect(page.getByRole('heading', { name: '任务详情' })).toBeVisible()
    await page.screenshot({ path: 'test-results/task-detail.png', fullPage: true })
    await page.getByRole('tab', { name: '活动日志', exact: true }).click()
    await expect(page.locator('.activity-log')).toContainText('下载完成')
    await page.getByRole('button', { name: 'Close', exact: true }).click()
    await page.getByRole('button', { name: '卡片视图' }).click()
    await page.getByRole('textbox', { name: '搜索任务' }).fill('no-matching-title')
    await expect(page.getByRole('heading', { name: '没有匹配的任务' })).toBeVisible()
    await page.getByRole('textbox', { name: '搜索任务' }).fill('')
    await page.getByRole('button', { name: '设置', exact: true }).click()
    await page.getByRole('tab', { name: '下载', exact: true }).click()
    await page.getByRole('spinbutton', { name: '同时下载任务数' }).fill('1')
    await page.getByRole('button', { name: '保存设置' }).click()
    await expect(page.getByRole('status')).toHaveText('设置已保存')
    await page.screenshot({ path: 'test-results/settings.png', fullPage: true })
    await page.getByRole('tab', { name: '外观', exact: true }).click()
    await page.getByRole('combobox', { name: '主题', exact: true }).click()
    await page.getByRole('option', { name: '夜间', exact: true }).click()
    await page.getByRole('button', { name: '保存设置' }).click()
    await expect(page.locator('html')).toHaveClass('dark')
    await page.getByRole('combobox', { name: '主题', exact: true }).click()
    await page.getByRole('option', { name: '浅色', exact: true }).click()
    await page.getByRole('button', { name: '保存设置' }).click()
    await expect(page.locator('html')).not.toHaveClass('dark')
    await page.getByRole('combobox', { name: '主题', exact: true }).click()
    await page.getByRole('option', { name: '夜间', exact: true }).click()
    await page.getByRole('button', { name: '保存设置' }).click()
    await expect(page.locator('html')).toHaveClass('dark')
    await page.getByRole('button', { name: /^已完成/ }).click()
    expect(errors).toEqual([])
    await page.screenshot({ path: 'test-results/client.png', fullPage: true })
    await app.close()
    app = await electron.launch({ args: ['.', '--no-sandbox'], cwd: root, env })
    page = await app.firstWindow()
    await page.getByRole('button', { name: /^已完成/ }).click()
    await expect(page.getByRole('button', { name: '打开文件位置' })).toBeVisible()
    await expect(page.getByRole('button', { name: '卡片视图' })).toHaveAttribute('aria-pressed', 'true')
    const restored = await page.evaluate(() => window.desktopApi.command('state:get', null))
    expect(restored.ok && restored.state.settings.concurrency).toBe(1)
  } finally {
    await app.close()
    await new Promise<void>(resolve => { server.closeAllConnections(); server.close(() => resolve()) })
    await rm(directory, { recursive: true, force: true })
  }
})
