import { spawn } from 'node:child_process'
import { createInterface } from 'node:readline'
import { existsSync } from 'node:fs'
import path from 'node:path'
import { logger } from './log'
import { i18n } from '../../shared/i18n'

const log = logger('engine')

export type Cookie = { name: string; value: string; domain: string; path: string; secure: boolean; expires: number }
export type EngineEvent = { kind: string; message?: string; status?: string; downloaded?: number; total?: number; speed?: number; eta?: number; result?: unknown }
export type EngineProfile = { browser: string; path: string }
export type EngineRequest = {
  operation: 'version' | 'extract' | 'download'; profile?: EngineProfile; cookies?: Cookie[];
  speedLimit?: number; retries?: number; timeout?: number; audioFormat?: string;
  subtitles?: 'off' | 'embed' | 'file'; subtitleLanguages?: string; subtitleAutoGenerated?: boolean;
  saveThumbnail?: boolean; embedThumbnail?: boolean; thumbnailFormat?: 'original' | 'jpg';
  url?: string; format?: string; output?: string; audioOnly?: boolean; entry?: number; headers?: Record<string, string>; flat?: boolean
}

export function redact(message: string): string {
  return message.replace(/https?:\/\/[^\s"'<>]+/gi, value => {
    try { const url = new URL(value); return `${url.origin}${url.pathname}${url.search ? '?[redacted]' : ''}` } catch { return '[url]' }
  }).replace(/((?:cookie|authorization|token|password)\s*[:=]\s*)[^\r\n]+/gi, '$1[redacted]').slice(0, 2000)
}

// Node's process API provides bounded pipes and cancellation; no shell wrapper or command-string library is needed.
export function runProcess<T>(executable: string, args: string[], input: unknown, signal?: AbortSignal, onEvent?: (event: EngineEvent) => void, timeout = 120_000): Promise<T> {
  signal?.throwIfAborted()
  return new Promise((resolve, reject) => {
    const child = spawn(executable, args, { shell: false, windowsHide: true, detached: process.platform !== 'win32', stdio: ['pipe', 'pipe', 'pipe'], env: { ...process.env, ELECTRON_RUN_AS_NODE: '1', PYTHONUNBUFFERED: '1' } })
    let result: T | undefined
    let error = ''
    let bytes = 0
    let timedOut = false
    const started = Date.now()
    // What the call was for, without the cookies and headers it carries.
    const request = input as { operation?: string; url?: string } | undefined
    const label = `${request?.operation || path.basename(executable)}${request?.url ? ` ${request.url}` : ''}`
    log.debug(`开始 ${label}`)
    const stop = () => {
      if (!child.pid) return
      if (process.platform === 'win32') spawn('taskkill', ['/pid', String(child.pid), '/T', '/F'], { windowsHide: true, stdio: 'ignore' }).on('error', () => child.kill())
      else { try { process.kill(-child.pid, 'SIGTERM') } catch { child.kill() } }
    }
    const timer = setTimeout(() => { timedOut = true; stop() }, timeout)
    signal?.addEventListener('abort', stop, { once: true })
    const output = createInterface({ input: child.stdout })
    output.on('line', line => {
      bytes += line.length
      if (bytes > 32 * 1024 * 1024) { error = i18n.t('queue:errors.engineOutputTooLarge'); stop(); return }
      try {
        const event = JSON.parse(line) as EngineEvent
        if (event.kind === 'result') result = event.result as T
        else if (event.kind === 'error') error = redact(event.message || i18n.t('queue:errors.engineFailed'))
        else {
          // yt-dlp's own messages. A caller that listens - a download - files them in the job's log,
          // which reaches this file too; progress ticks are left out, there are hundreds of them.
          if (!onEvent && event.kind === 'log' && event.message) log.debug(`yt-dlp：${event.message}`)
          onEvent?.(event)
        }
      } catch { log.debug(`非协议输出：${line.slice(0, 500)}`) }
    })
    child.stderr.on('data', chunk => { error = (error + redact(String(chunk))).slice(-4000) })
    child.stdin.on('error', () => { /* Early process exit is handled by close. */ })
    child.on('error', failure => { error = failure.message })
    child.on('close', code => {
      clearTimeout(timer)
      signal?.removeEventListener('abort', stop)
      output.close()
      const took = `${Date.now() - started}ms`
      if (signal?.aborted) { log.info(`取消 ${label} ${took}`); reject(new DOMException(i18n.t('queue:errors.cancelled'), 'AbortError')) }
      else if (timedOut) { log.warn(`超时 ${label} ${took}`); reject(new Error(i18n.t('queue:errors.timeout'))) }
      else if (code !== 0 || result === undefined) { log.warn(`失败 ${label} 退出码 ${code} ${took}：${error.slice(-1500)}`); reject(new Error(error || i18n.t('queue:errors.engineExited', { code: String(code) }))) }
      else { log.info(`完成 ${label} ${took}`); resolve(result) }
    })
    child.stdin.end(JSON.stringify(input))
  })
}

export class Engine {
  // YouTube serves machine-translated titles and descriptions, defaulting to English. The interface
  // language decides which translation the extractor asks for.
  constructor(private root: string, private resources: string, private packaged: boolean, private locale: () => string = () => 'en') {}

  get ffmpeg(): string {
    const name = process.platform === 'win32' ? 'ffmpeg.exe' : 'ffmpeg'
    const bundled = path.join(this.resources, 'engine', name)
    const local = path.join(this.root, 'node_modules', 'ffmpeg-static', name)
    if (existsSync(bundled)) return bundled
    if (!this.packaged && existsSync(local)) return local
    throw new Error(i18n.t('queue:errors.ffmpegMissing'))
  }

  private get command(): [string, string[]] {
    const binary = path.join(this.resources, 'engine', process.platform === 'win32' ? 'media-engine.exe' : 'media-engine')
    if (existsSync(binary)) return [binary, []]
    const python = path.join(this.root, '.venv', process.platform === 'win32' ? 'Scripts/python.exe' : 'bin/python')
    if (!this.packaged && existsSync(python)) return [python, [path.join(this.root, 'engine/main.py')]]
    throw new Error(i18n.t('queue:errors.engineMissing'))
  }

  request<T>(request: EngineRequest, signal?: AbortSignal, onEvent?: (event: EngineEvent) => void): Promise<T> {
    const [executable, args] = this.command
    return runProcess<T>(executable, args, { ...request, locale: this.locale(), ffmpeg: request.operation === 'version' ? undefined : this.ffmpeg, node: process.execPath }, signal, onEvent, request.operation === 'download' ? 24 * 60 * 60 * 1000 : request.operation === 'extract' ? 300_000 : 120_000)
  }
}
