import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { FolderOpen, RefreshCw, Save } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card'
import { Field, FieldDescription, FieldGroup, FieldLabel, FieldSet, FieldLegend, FieldTitle } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { Item, ItemActions, ItemContent, ItemDescription, ItemTitle } from '@/components/ui/item'
import { Progress } from '@/components/ui/progress'
import { Switch } from '@/components/ui/switch'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Choice } from './Choice'
import type { ClientState, Settings } from '../../../shared/contracts'
import type { Send } from '@/App'

const sections = ['general', 'download', 'files', 'browser', 'appearance', 'tools'] as const
type Section = typeof sections[number]
export function Preferences({ state, send }: { state: ClientState; send: Send }) {
  const { t } = useTranslation(['settings', 'common'])
  const [draft, setDraft] = useState(state.settings)
  useEffect(() => { setDraft(current => ({ ...current, theme: state.settings.theme })) }, [state.settings.theme])
  const [section, setSection] = useState<Section>('general')
  const [saved, setSaved] = useState(false)
  const [saving, setSaving] = useState(false)
  const patch = (value: Partial<Settings>) => { setDraft(current => ({ ...current, ...value })); setSaved(false) }
  const number = (key: 'concurrency' | 'speedLimit' | 'taskSpeedLimit' | 'retries' | 'timeout' | 'batchLimit', label: string, min: number, max: number, hint: string) => <Field>
    <FieldLabel htmlFor={`setting-${key}`}>{label}</FieldLabel>
    <Input id={`setting-${key}`} aria-label={label} type="number" required min={min} max={max} value={draft[key]} onChange={event => patch({ [key]: event.target.valueAsNumber })} />
    <FieldDescription>{hint}</FieldDescription>
  </Field>
  const toggle = (key: 'resumeOnStart' | 'notifications' | 'minimizeToTray' | 'organizeByPlatform' | 'organizeByCollection' | 'saveThumbnail' | 'embedThumbnailInVideo' | 'embedThumbnailInAudio' | 'subtitleAutoGenerated' | 'subtitleNormalizeOverlaps' | 'keepHistory' | 'verboseLogging' | 'allowControl', label: string, hint: string) => <Field orientation="horizontal">
    <FieldContentLabel id={`toggle-${key}`} label={label} hint={hint} />
    <Switch aria-labelledby={`toggle-${key}`} checked={draft[key]} onCheckedChange={checked => patch({ [key]: checked })} />
  </Field>
  return <form onSubmit={event => { event.preventDefault(); setSaving(true); void send('settings:save', draft).then(ok => setSaved(Boolean(ok))).finally(() => setSaving(false)) }}>
    <Card>
      <CardHeader>
        <CardTitle>{t('title')}</CardTitle>
        <CardDescription>{t('description')}</CardDescription>
      </CardHeader>
      <CardContent>
        {/* A side menu read like the app's own sidebar: rows of the same height, the open one filled
            rather than underlined, and a rule between it and the fields it switches. */}
        <Tabs orientation="vertical" value={section} onValueChange={value => setSection(value as Section)} className="gap-6">
          <TabsList className="w-44 shrink-0 items-stretch gap-1 self-stretch rounded-none border-r bg-transparent p-0 pr-4">{sections.map(id =>
            <TabsTrigger key={id} value={id} className="h-9 flex-none justify-start rounded-md border-0 px-3 font-normal hover:bg-muted/60 data-active:bg-muted data-active:font-medium dark:data-active:border-transparent dark:data-active:bg-muted group-data-[variant=default]/tabs-list:data-active:shadow-none">{t(`sections.${id}`)}</TabsTrigger>)}
          </TabsList>
          <TabsContent value="general"><FieldGroup>
            <Field>
              <FieldLabel>{t('general.saveLocation')}</FieldLabel>
              <Button type="button" variant="outline" className="justify-start overflow-hidden" onClick={() => void send('settings:directory', null)}><FolderOpen /><span className="truncate">{state.settings.downloadDirectory}</span></Button>
              <FieldDescription>{t('general.saveLocationHint')}</FieldDescription>
            </Field>
            {toggle('resumeOnStart', t('general.resumeOnStart.label'), t('general.resumeOnStart.hint'))}
            {toggle('notifications', t('general.notifications.label'), t('general.notifications.hint'))}
            {toggle('minimizeToTray', t('general.minimizeToTray.label'), t('general.minimizeToTray.hint'))}
            {toggle('keepHistory', t('general.keepHistory.label'), t('general.keepHistory.hint'))}
          </FieldGroup></TabsContent>
          <TabsContent value="download"><FieldGroup>
            <div className="grid gap-4 sm:grid-cols-2">
              {number('concurrency', t('download.concurrency.label'), 1, 4, t('download.concurrency.hint'))}
              {number('speedLimit', t('download.speedLimit.label'), 0, 1048576, t('download.speedLimit.hint'))}
              {number('taskSpeedLimit', t('download.taskSpeedLimit.label'), 0, 1048576, t('download.taskSpeedLimit.hint'))}
              {number('timeout', t('download.timeout.label'), 5, 300, t('download.timeout.hint'))}
              {number('retries', t('download.retries.label'), 0, 10, t('download.retries.hint'))}
              {number('batchLimit', t('download.batchLimit.label'), 0, 500, t('download.batchLimit.hint'))}
            </div>
          </FieldGroup></TabsContent>
          <TabsContent value="files"><FieldGroup>
            <Choice label={t('files.naming.label')} value={draft.filenameTemplate} onChange={value => patch({ filenameTemplate: value as Settings['filenameTemplate'] })} options={[{ value: 'title-id', label: t('files.naming.titleId') }, { value: 'id-title', label: t('files.naming.idTitle') }, { value: 'date-title-id', label: t('files.naming.dateTitleId') }]} />
            <FieldDescription>{t('files.namingHint')}</FieldDescription>
            {toggle('organizeByPlatform', t('files.organizeByPlatform.label'), t('files.organizeByPlatform.hint'))}
            {toggle('organizeByCollection', t('files.organizeByCollection.label'), t('files.organizeByCollection.hint'))}
            <div className="grid gap-4 sm:grid-cols-2">
              <Choice label={t('files.videoQuality.label')} value={draft.videoQuality} onChange={value => patch({ videoQuality: value as Settings['videoQuality'] })} options={[{ value: 'best', label: t('files.videoQuality.best') }, ...['1080', '720', '480'].map(value => ({ value, label: t('files.videoQuality.upTo', { height: value }) }))]} />
              <Choice label={t('files.audioFormat.label')} value={draft.audioFormat} onChange={value => patch({ audioFormat: value as Settings['audioFormat'] })} options={[{ value: 'best', label: t('files.audioFormat.best') }, ...['mp3', 'm4a', 'flac'].map(value => ({ value, label: t('files.audioFormat.convert', { format: value.toUpperCase() }) }))]} />
            </div>
            <FieldDescription>{t('files.mergeHint')}</FieldDescription>
            <FieldSet>
              <FieldLegend variant="label">{t('files.cover.legend')}</FieldLegend>
              <FieldGroup className="gap-4">
                {toggle('saveThumbnail', t('files.cover.save.label'), t('files.cover.save.hint'))}
                {toggle('embedThumbnailInVideo', t('files.cover.embedVideo.label'), t('files.cover.embedVideo.hint'))}
                {toggle('embedThumbnailInAudio', t('files.cover.embedAudio.label'), t('files.cover.embedAudio.hint'))}
                <Choice label={t('files.cover.format.label')} value={draft.thumbnailFormat} onChange={value => patch({ thumbnailFormat: value as Settings['thumbnailFormat'] })} options={[{ value: 'original', label: t('files.cover.format.original') }, { value: 'jpg', label: t('files.cover.format.jpg') }]} />
                <FieldDescription>{t('files.cover.hint')}</FieldDescription>
              </FieldGroup>
            </FieldSet>
            <FieldSet>
              <FieldLegend variant="label">{t('files.subtitles.legend')}</FieldLegend>
              <FieldGroup className="gap-4">
                <div className="grid gap-4 sm:grid-cols-2">
                  <Choice label={t('files.subtitles.label')} value={draft.subtitles} onChange={value => patch({ subtitles: value as Settings['subtitles'] })} options={[{ value: 'embed', label: t('files.subtitles.embed') }, { value: 'file', label: t('files.subtitles.file') }, { value: 'off', label: t('files.subtitles.off') }]} />
                  <Field data-disabled={draft.subtitles === 'off' || undefined}>
                    <FieldLabel htmlFor="setting-subtitle-languages">{t('files.subtitles.languages')}</FieldLabel>
                    <Input id="setting-subtitle-languages" aria-label={t('files.subtitles.languages')} value={draft.subtitleLanguages} onChange={event => patch({ subtitleLanguages: event.target.value })} placeholder={t('files.subtitles.languagesPlaceholder')} disabled={draft.subtitles === 'off'} />
                    <FieldDescription>{t('files.subtitles.languagesHint')}</FieldDescription>
                  </Field>
                </div>
                {toggle('subtitleAutoGenerated', t('files.subtitles.autoGenerated.label'), t('files.subtitles.autoGenerated.hint'))}
                {toggle('subtitleNormalizeOverlaps', t('files.subtitles.normalize.label'), t('files.subtitles.normalize.hint'))}
                <FieldDescription>{t('files.subtitles.hint')}</FieldDescription>
              </FieldGroup>
            </FieldSet>
          </FieldGroup></TabsContent>
          <TabsContent value="browser"><FieldGroup>
            <Item variant="muted">
              <ItemContent>
                <ItemTitle>{t('browser.systemTitle')}</ItemTitle>
                <ItemDescription className="whitespace-normal">{t('browser.systemDescription', { browser: state.profiles.find(profile => profile.id === state.settings.browserProfileId)?.label || t('browser.noBrowser') })}</ItemDescription>
              </ItemContent>
            </Item>
            <Button type="button" variant="outline" className="w-fit" onClick={() => void send('browser:refresh', null)}><RefreshCw />{t('browser.redetect')}</Button>
            <Item variant="muted">
              <ItemContent>
                <ItemTitle>{state.browser.sites ? t('browser.sessions', { count: state.browser.sites }) : t('browser.noSessions')}</ItemTitle>
                <ItemDescription className="whitespace-normal">{t('browser.sessionsHint')}</ItemDescription>
              </ItemContent>
            </Item>
            <div className="flex flex-wrap gap-2">
              <Button type="button" variant="outline" onClick={() => void send('browser:login', { url: '' })}>{t('common:openLogin')}</Button>
              <Button type="button" variant="outline" onClick={() => void send('browser:clear', null)}>{t('browser.clearSessions')}</Button>
            </div>
          </FieldGroup></TabsContent>
          <TabsContent value="appearance"><FieldGroup>
            {/* Labelled in both languages and applied at once, so whoever switched to the one they do not
                read can still find the way back. */}
            <Choice label="语言 · Language" value={state.settings.locale} onChange={value => { patch({ locale: value as Settings['locale'] }); void send('settings:save', { ...state.settings, locale: value as Settings['locale'] }) }} options={[{ value: 'zh', label: '中文' }, { value: 'en', label: 'English' }]} />
            <Choice label={t('appearance.theme.label')} value={draft.theme} onChange={value => patch({ theme: value as Settings['theme'] })} options={[{ value: 'system', label: t('appearance.theme.system') }, { value: 'light', label: t('appearance.theme.light') }, { value: 'dark', label: t('appearance.theme.dark') }]} />
            <Choice label={t('appearance.view.label')} value={draft.view} onChange={value => patch({ view: value as Settings['view'] })} options={[{ value: 'list', label: t('appearance.view.list') }, { value: 'grid', label: t('appearance.view.grid') }]} />
            <Choice label={t('appearance.resultView.label')} value={draft.resultView} onChange={value => patch({ resultView: value as Settings['resultView'] })} options={[{ value: 'auto', label: t('appearance.resultView.auto') }, { value: 'list', label: t('appearance.resultView.list') }, { value: 'grid', label: t('appearance.resultView.grid') }]} />
            <Choice label={t('appearance.density.label')} value={draft.density} onChange={value => patch({ density: value as Settings['density'] })} options={[{ value: 'comfortable', label: t('appearance.density.comfortable') }, { value: 'compact', label: t('appearance.density.compact') }]} />
          </FieldGroup></TabsContent>
          <TabsContent value="tools"><FieldGroup>
            <Item variant="muted">
              <ItemContent>
                <ItemTitle>yt-dlp</ItemTitle>
                <ItemDescription className="break-all whitespace-normal">{state.tools.engine.available ? state.tools.engine.version : state.tools.engine.error || t('tools.checking')}</ItemDescription>
                <ItemTitle>FFmpeg</ItemTitle>
                <ItemDescription className="break-all whitespace-normal">{state.tools.ffmpeg.available ? state.tools.ffmpeg.version : state.tools.ffmpeg.error || t('tools.checking')}</ItemDescription>
                <ItemDescription>{t('tools.localHint')}</ItemDescription>
              </ItemContent>
            </Item>
            <div className="flex flex-wrap gap-2">
              <Button type="button" variant="outline" onClick={() => void send('tools:check', null)}>{t('tools.checkTools')}</Button>
              <Button type="button" variant="outline" disabled={['checking', 'downloading'].includes(state.update.status)} onClick={() => void send('update:check', null)}>{t('tools.checkUpdate')}</Button>
              {state.update.status === 'available' && <Button type="button" onClick={() => void send('update:download', null)}>{t('tools.downloadUpdate', { version: state.update.version })}</Button>}
              {state.update.status === 'ready' && <Button type="button" onClick={() => void send('update:install', null)}>{t('tools.installUpdate')}</Button>}
            </div>
            {state.update.status === 'downloading' && <Progress value={state.update.progress ?? 0} />}
            {state.update.message && <p className="text-sm">{state.update.message}</p>}
            {toggle('verboseLogging', t('tools.verboseLogging.label'), t('tools.verboseLogging.hint'))}
            {toggle('allowControl', t('tools.allowControl.label'), t('tools.allowControl.hint'))}
            {/* Installed at once rather than on 保存设置: it writes files and the PATH, not a setting. */}
            <Item variant="muted">
              <ItemContent>
                <ItemTitle>{t('tools.commandLine.title')}</ItemTitle>
                <ItemDescription className="whitespace-normal">{state.commandLine.installed ? t('tools.commandLine.installed', { path: state.commandLine.launcher }) : t('tools.commandLine.hint')}</ItemDescription>
                {state.commandLine.installed && !state.commandLine.onPath && <ItemDescription className="whitespace-normal">{t('tools.commandLine.notOnPath')}</ItemDescription>}
              </ItemContent>
              <ItemActions>
                <Button type="button" variant="outline" onClick={() => void send(state.commandLine.installed ? 'cli:uninstall' : 'cli:install', null)}>{state.commandLine.installed ? t('tools.commandLine.uninstall') : t('tools.commandLine.install')}</Button>
              </ItemActions>
            </Item>
            <div className="flex flex-wrap gap-2">
              <Button type="button" variant="outline" onClick={() => void send('logs:open', null)}>{t('tools.openLogs')}</Button>
              <Button type="button" variant="outline" onClick={() => void send('logs:export', null)}>{t('tools.exportLogs')}</Button>
            </div>
          </FieldGroup></TabsContent>
        </Tabs>
      </CardContent>
      <CardFooter className="gap-3 border-t">
        <Button type="submit" disabled={saving}><Save />{saving ? t('saving') : t('save')}</Button>
        <span role="status" className="text-sm text-muted-foreground">{saved ? t('saved') : ''}</span>
      </CardFooter>
    </Card>
  </form>
}
function FieldContentLabel({ id, label, hint }: { id: string; label: string; hint: string }) {
  return <div className="grid gap-1">
    <FieldTitle id={id}>{label}</FieldTitle>
    <FieldDescription>{hint}</FieldDescription>
  </div>
}
