import { useEffect, useState } from 'react'
import { FolderOpen, RefreshCw, Save } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card'
import { Field, FieldDescription, FieldGroup, FieldLabel, FieldSet, FieldLegend, FieldTitle } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { Item, ItemContent, ItemDescription, ItemTitle } from '@/components/ui/item'
import { Progress } from '@/components/ui/progress'
import { Switch } from '@/components/ui/switch'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Choice } from './Choice'
import type { ClientState, Settings } from '../../../shared/contracts'
import type { Send } from '@/App'

const sections = ['常规', '下载', '文件与媒体', '浏览器', '外观', '工具与更新']
export function Preferences({ state, send }: { state: ClientState; send: Send }) {
  const [draft, setDraft] = useState(state.settings)
  useEffect(() => { setDraft(current => ({ ...current, theme: state.settings.theme })) }, [state.settings.theme])
  const [section, setSection] = useState('常规')
  const [saved, setSaved] = useState(false)
  const [saving, setSaving] = useState(false)
  const patch = (value: Partial<Settings>) => { setDraft(current => ({ ...current, ...value })); setSaved(false) }
  const number = (key: 'concurrency' | 'speedLimit' | 'taskSpeedLimit' | 'retries' | 'timeout' | 'batchLimit', label: string, min: number, max: number, hint: string) => <Field>
    <FieldLabel htmlFor={`setting-${key}`}>{label}</FieldLabel>
    <Input id={`setting-${key}`} aria-label={label} type="number" required min={min} max={max} value={draft[key]} onChange={event => patch({ [key]: event.target.valueAsNumber })} />
    <FieldDescription>{hint}</FieldDescription>
  </Field>
  const toggle = (key: 'resumeOnStart' | 'notifications' | 'minimizeToTray' | 'organizeByPlatform' | 'organizeByCollection' | 'saveThumbnail' | 'embedThumbnailInVideo' | 'embedThumbnailInAudio' | 'subtitleAutoGenerated' | 'keepHistory' | 'verboseLogging', label: string, hint: string) => <Field orientation="horizontal">
    <FieldContentLabel id={`toggle-${key}`} label={label} hint={hint} />
    <Switch aria-labelledby={`toggle-${key}`} checked={draft[key]} onCheckedChange={checked => patch({ [key]: checked })} />
  </Field>
  return <form onSubmit={event => { event.preventDefault(); setSaving(true); void send('settings:save', draft).then(ok => setSaved(Boolean(ok))).finally(() => setSaving(false)) }}>
    <Card>
      <CardHeader>
        <CardTitle>设置</CardTitle>
        <CardDescription>设置保存在本机。下载参数在新建或继续任务时生效。</CardDescription>
      </CardHeader>
      <CardContent>
        {/* A side menu read like the app's own sidebar: rows of the same height, the open one filled
            rather than underlined, and a rule between it and the fields it switches. */}
        <Tabs orientation="vertical" value={section} onValueChange={value => setSection(String(value))} className="gap-6">
          <TabsList className="w-44 shrink-0 items-stretch gap-1 self-stretch rounded-none border-r bg-transparent p-0 pr-4">{sections.map(name =>
            <TabsTrigger key={name} value={name} className="h-9 flex-none justify-start rounded-md border-0 px-3 font-normal hover:bg-muted/60 data-active:bg-muted data-active:font-medium dark:data-active:border-transparent dark:data-active:bg-muted group-data-[variant=default]/tabs-list:data-active:shadow-none">{name}</TabsTrigger>)}
          </TabsList>
          <TabsContent value="常规"><FieldGroup>
            <Field>
              <FieldLabel>保存位置</FieldLabel>
              <Button type="button" variant="outline" className="justify-start overflow-hidden" onClick={() => void send('settings:directory', null)}><FolderOpen /><span className="truncate">{state.settings.downloadDirectory}</span></Button>
              <FieldDescription>目录选择后立即保存，只影响新建任务。</FieldDescription>
            </Field>
            {toggle('resumeOnStart', '启动时恢复任务', '继续上次退出时正在下载和等待中的任务。')}
            {toggle('notifications', '下载完成通知', '通过系统通知提醒文件已保存。')}
            {toggle('minimizeToTray', '关闭窗口时保留后台下载', '最小化到系统托盘；使用托盘菜单退出应用。')}
            {toggle('keepHistory', '保存解析历史', '在新建任务页记住解析成功的链接，方便再次解析；只保存在本机。关闭后不再记录，已有的记录可在新建任务页清空。')}
          </FieldGroup></TabsContent>
          <TabsContent value="下载"><FieldGroup>
            <div className="grid gap-4 sm:grid-cols-2">
              {number('concurrency', '同时下载任务数', 1, 4, '最多 4 个任务并行下载。')}
              {number('speedLimit', '全局限速（KiB/s）', 0, 1048576, '0 为不限速；额度按并发槽位均分。')}
              {number('taskSpeedLimit', '默认单任务限速（KiB/s）', 0, 1048576, '0 为不限速；可在任务详情单独调整。')}
              {number('timeout', '连接超时（秒）', 5, 300, '连接或媒体读取长时间无响应时重试。')}
              {number('retries', '下载重试次数', 0, 10, '文件或分片失败后重试；耗尽后可手动重试。')}
              {number('batchLimit', '单次批量上限', 0, 500, '一次点「下载所选」最多入队多少项，按列表顺序取前面的。0 表示不限。')}
            </div>
          </FieldGroup></TabsContent>
          <TabsContent value="文件与媒体"><FieldGroup>
            <Choice label="文件命名" value={draft.filenameTemplate} onChange={value => patch({ filenameTemplate: value as Settings['filenameTemplate'] })} options={[{ value: 'title-id', label: '标题-任务编号' }, { value: 'id-title', label: '任务编号-标题' }, { value: 'date-title-id', label: '日期-标题-任务编号' }]} />
            <FieldDescription>任务编号避免同名覆盖。重试使用原文件名，支持时续传。</FieldDescription>
            {toggle('organizeByPlatform', '按平台创建子目录', '新任务自动保存到对应平台文件夹。')}
            {toggle('organizeByCollection', '按合集创建子目录', '合集与分P 保存到以合集名命名的文件夹；与上一项同时开启时为 平台/合集。')}
            <div className="grid gap-4 sm:grid-cols-2">
              <Choice label="默认视频质量" value={draft.videoQuality} onChange={value => patch({ videoQuality: value as Settings['videoQuality'] })} options={[{ value: 'best', label: '最佳可用画质' }, { value: '1080', label: '最高 1080p' }, { value: '720', label: '最高 720p' }, { value: '480', label: '最高 480p' }]} />
              <Choice label="音频格式" value={draft.audioFormat} onChange={value => patch({ audioFormat: value as Settings['audioFormat'] })} options={[{ value: 'best', label: '最高音质（不转码）' }, ...['mp3', 'm4a', 'flac'].map(value => ({ value, label: `转为 ${value.toUpperCase()}` }))]} />
            </div>
            <FieldDescription>分离的音视频自动合并。图文保留原始图片格式。</FieldDescription>
            <FieldSet>
              <FieldLegend variant="label">封面</FieldLegend>
              <FieldGroup className="gap-4">
                {toggle('saveThumbnail', '下载视频时保存封面图片', '在视频旁边多存一张同名封面图。')}
                {toggle('embedThumbnailInVideo', '把封面嵌进视频文件', '让封面成为视频文件自己的封面图；部分播放器与资源管理器不读 MP4 的封面轨。')}
                {toggle('embedThumbnailInAudio', '仅音频下载时嵌入封面', '音频文件带上封面图，播放器按专辑封面显示。')}
                <Choice label="封面保存格式" value={draft.thumbnailFormat} onChange={value => patch({ thumbnailFormat: value as Settings['thumbnailFormat'] })} options={[{ value: 'original', label: '平台原始格式' }, { value: 'jpg', label: '统一转为 JPG' }]} />
                <FieldDescription>平台多数给的是 WebP，Windows 资源管理器对它的缩略图支持不一致。图文作品不额外存封面——作品本身就是图片。任务右键的「下载封面」随时可用，不受这些开关影响。</FieldDescription>
              </FieldGroup>
            </FieldSet>
            <FieldSet>
              <FieldLegend variant="label">字幕</FieldLegend>
              <FieldGroup className="gap-4">
                <div className="grid gap-4 sm:grid-cols-2">
                  <Choice label="字幕" value={draft.subtitles} onChange={value => patch({ subtitles: value as Settings['subtitles'] })} options={[{ value: 'embed', label: '嵌入视频文件' }, { value: 'file', label: '保存为独立字幕文件' }, { value: 'off', label: '不下载字幕' }]} />
                  <Field data-disabled={draft.subtitles === 'off' || undefined}>
                    <FieldLabel htmlFor="setting-subtitle-languages">字幕语言</FieldLabel>
                    <Input id="setting-subtitle-languages" aria-label="字幕语言" value={draft.subtitleLanguages} onChange={event => patch({ subtitleLanguages: event.target.value })} placeholder="留空跟随界面语言" disabled={draft.subtitles === 'off'} />
                    <FieldDescription>逗号分隔，按优先级排列；填 all 下载全部语言。</FieldDescription>
                  </Field>
                </div>
                {toggle('subtitleAutoGenerated', '使用自动生成字幕', '该语言没有人工字幕时，回退到平台的语音识别字幕。')}
                <FieldDescription>仅对提供字幕轨的平台有效，YouTube 和登录后的 B 站支持最好。嵌入 MP4 时字幕转为 mov_text，个别播放器可能不显示。</FieldDescription>
              </FieldGroup>
            </FieldSet>
          </FieldGroup></TabsContent>
          <TabsContent value="浏览器"><FieldGroup>
            <Item variant="muted">
              <ItemContent>
                <ItemTitle>尝试读取的系统浏览器</ItemTitle>
                <ItemDescription className="whitespace-normal">{state.profiles.find(profile => profile.id === state.settings.browserProfileId)?.label || '尚未检测到可用浏览器'}。解析时先尝试直接读取它的登录态。系统加密或浏览器占用导致读取失败时会自动跳过，不影响公开内容。</ItemDescription>
              </ItemContent>
            </Item>
            <Button type="button" variant="outline" className="w-fit" onClick={() => void send('browser:refresh', null)}><RefreshCw />重新检测</Button>
            <Item variant="muted">
              <ItemContent>
                <ItemTitle>{state.browser.sites ? `应用内浏览器 · ${state.browser.sites} 个站点有会话` : '应用内浏览器暂无会话'}</ItemTitle>
                <ItemDescription className="whitespace-normal">需要登录的内容在应用内登录一次即可，登录态保存在本机，重启后继续有效。</ItemDescription>
              </ItemContent>
            </Item>
            <div className="flex flex-wrap gap-2">
              <Button type="button" variant="outline" onClick={() => void send('browser:login', { url: '' })}>打开登录窗口</Button>
              <Button type="button" variant="outline" onClick={() => void send('browser:clear', null)}>清除登录态</Button>
            </div>
          </FieldGroup></TabsContent>
          <TabsContent value="外观"><FieldGroup>
            <Choice label="主题" value={draft.theme} onChange={value => patch({ theme: value as Settings['theme'] })} options={[{ value: 'system', label: '跟随系统' }, { value: 'light', label: '浅色' }, { value: 'dark', label: '夜间' }]} />
            <Choice label="默认视图" value={draft.view} onChange={value => patch({ view: value as Settings['view'] })} options={[{ value: 'list', label: '列表' }, { value: 'grid', label: '封面卡片' }]} />
            <Choice label="解析结果视图" value={draft.resultView} onChange={value => patch({ resultView: value as Settings['resultView'] })} options={[{ value: 'auto', label: '自动（按内容）' }, { value: 'list', label: '列表' }, { value: 'grid', label: '缩略图' }]} />
            <Choice label="列表密度" value={draft.density} onChange={value => patch({ density: value as Settings['density'] })} options={[{ value: 'comfortable', label: '舒适' }, { value: 'compact', label: '紧凑' }]} />
          </FieldGroup></TabsContent>
          <TabsContent value="工具与更新"><FieldGroup>
            <Item variant="muted">
              <ItemContent>
                <ItemTitle>yt-dlp</ItemTitle>
                <ItemDescription className="break-all whitespace-normal">{state.tools.engine.available ? state.tools.engine.version : state.tools.engine.error || '检测中'}</ItemDescription>
                <ItemTitle>FFmpeg</ItemTitle>
                <ItemDescription className="break-all whitespace-normal">{state.tools.ffmpeg.available ? state.tools.ffmpeg.version : state.tools.ffmpeg.error || '检测中'}</ItemDescription>
                <ItemDescription>本地工具随应用更新，下载和解析均在本机执行。</ItemDescription>
              </ItemContent>
            </Item>
            <div className="flex flex-wrap gap-2">
              <Button type="button" variant="outline" onClick={() => void send('tools:check', null)}>检测工具</Button>
              <Button type="button" variant="outline" disabled={['checking', 'downloading'].includes(state.update.status)} onClick={() => void send('update:check', null)}>检查更新</Button>
              {state.update.status === 'available' && <Button type="button" onClick={() => void send('update:download', null)}>下载 {state.update.version}</Button>}
              {state.update.status === 'ready' && <Button type="button" onClick={() => void send('update:install', null)}>重启安装</Button>}
            </div>
            {state.update.status === 'downloading' && <Progress value={state.update.progress ?? 0} />}
            {state.update.message && <p className="text-sm">{state.update.message}</p>}
            {toggle('verboseLogging', '详细日志', '把每个请求的状态码、耗时、等待和异常响应的开头写进日志，排查解析失败时打开。凭据类参数会脱敏，日志只保存在本机。保存设置后生效。')}
            <div className="flex flex-wrap gap-2">
              <Button type="button" variant="outline" onClick={() => void send('logs:open', null)}>打开日志目录</Button>
              <Button type="button" variant="outline" onClick={() => void send('logs:export', null)}>导出诊断日志</Button>
            </div>
          </FieldGroup></TabsContent>
        </Tabs>
      </CardContent>
      <CardFooter className="gap-3 border-t">
        <Button type="submit" disabled={saving}><Save />{saving ? '正在保存…' : '保存设置'}</Button>
        <span role="status" className="text-sm text-muted-foreground">{saved ? '设置已保存' : ''}</span>
      </CardFooter>
    </Card>
  </form>
}
function FieldContentLabel({ id, label, hint }: { id: string; label: string; hint: string }) {
  return <div className="grid gap-1">
    <FieldTitle id={id}>{label}</FieldTitle>
    <FieldDescription>{hint}</FieldDescription>
  </div>
}
